export const ACTION_TYPES = {
  FETCH_PARK: "PARK",
  FETCH_UNPARK: "UNPARK",
  FETCH_NEW_ENTRY: "ENTRY",
  FETCH_CARS: "FETCH_CARS",
  FETCH_ENTRIES: "FETCH_ENTRIES",
  FETCH_START: "FETCH_START",
  FETCH_PARK_ERROR: "FETCH_PARK_ERROR",
};
